# GET http://localhost:3001/api/bookVideo
# Content-Type: application/json


# POST http://localhost:3001/api/addVideo
# Content-Type: application/json

# {
#    "lessonId": 5,
#    "videoId": 10
# }

# POST http://localhost:3001/api/addVideo
# Content-Type: application/json

# {
#    "lessonId": 5,
#    "videoName": "test",
#    "videoLink": "test"
# }

# GET http://localhost:3001/api/repeatVideo
# Content-Type: application/json


# POST http://localhost:3001/api/deleteChapter
# Content-Type: application/json

# {
#    "chapterId": 10
# }